name: C++ CI
on:
  push:

jobs:
    build:
            runs-on: ubuntu-latest

            steps:
              - name: Checkout code
                uses: actions/checkout@v4


              - name: Compile
                run: g++ "131-A. cAPS lOCK.cpp" -o main
                
              - name: Run
                run: ./main